version: '3'
services:
  postgres:
   image: postgres
   ports:
    - "5432:5432"
   environment:
    - "POSTGRES_PASSWORD=akademia"
    - "POSTGRES_USER=akademia"
    - "POSTGRES_DB=akademia"
   volumes:
   - db-data:/var/lib/postgresql/data
volumes:
 db-data: